# Model example:
tasks:
  -
    run-state: true
    username: goplus
    repository: gop
    interval-seconds: 3600
    storage-location: /tmp/gop
    public-url: https://ingop.uiuing.com/mirror/gop
    public-json:
      source-key: other
      now-key: zh
  -
    run-state: true
    username: goplus
    repository: c2go
    interval-seconds: 3600
    storage-location: /tmp/c2go
    public-url: https://ingop.uiuing.com/mirror/gop/c2go
    public-json:
      source-key: other
      now-key: zh
