log-location: /tmp
tasks:
  -
    run-state: true
    username: goplus
    repository: gop
    interval-seconds: 3600
    storage-location: /tmp/gop
    download-url: https://ingop.uiuing.com/mirror/gop/
  -
    run-state: false
    username: goplus
    repository: c2go
    interval-seconds: 3600
    storage-location: /tmp/c2go
    download-url: https://ingop.uiuing.com/mirror/gop/c2go/